# Generated by Django 3.0.3 on 2020-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('elo', models.IntegerField()),
                ('time', models.IntegerField()),
                ('dim', models.IntegerField()),
            ],
        ),
    ]
