# Generated by Django 3.0.3 on 2020-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0002_queuegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuegame',
            name='dim',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queuegame',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
