# Generated by Django 3.0.3 on 2020-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0003_auto_20200213_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=50)),
                ('username2', models.CharField(max_length=50)),
                ('elo1', models.IntegerField()),
                ('elo2', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('dim', models.CharField(max_length=50)),
            ],
        ),
    ]
