# Generated by Django 3.0.3 on 2020-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0004_gaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
