# Generated by Django 3.0.3 on 2020-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0005_auto_20200214_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='elo',
            field=models.IntegerField(default=500),
        ),
    ]
