# Generated by Django 3.0.3 on 2020-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0006_auto_20200214_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='id_move',
            field=models.IntegerField(default=0),
        ),
    ]
