# Generated by Django 3.0.3 on 2020-02-17 16:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0008_gaming_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='moves',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0), default=0, max_length=362, size=81),
        ),
    ]
