# Generated by Django 3.0.3 on 2020-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0011_auto_20200218_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='timer1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaming',
            name='timer2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
