# Generated by Django 3.0.3 on 2020-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0012_auto_20200219_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaming',
            old_name='time',
            new_name='time1',
        ),
        migrations.AddField(
            model_name='gaming',
            name='time2',
            field=models.IntegerField(default=0),
        ),
    ]
