# Generated by Django 3.0.3 on 2020-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0013_auto_20200221_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='eat_ball',
            field=models.IntegerField(default=0),
        ),
    ]
