# Generated by Django 3.0.3 on 2020-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0014_gaming_eat_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaming',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
