# Generated by Django 3.0.3 on 2020-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0015_auto_20200224_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='pedine1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaming',
            name='pedine2',
            field=models.IntegerField(default=0),
        ),
    ]
