# Generated by Django 3.0.3 on 2020-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0016_auto_20200224_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='pass_flag',
            field=models.IntegerField(default=0),
        ),
    ]
