# Generated by Django 3.0.3 on 2020-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0017_gaming_pass_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=50)),
                ('loser', models.CharField(max_length=50)),
                ('hash_code', models.IntegerField(default=0)),
            ],
        ),
    ]
