# Generated by Django 3.0.3 on 2020-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0019_auto_20200225_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='victory',
            field=models.IntegerField(default=0),
        ),
    ]
