# Generated by Django 3.0.3 on 2020-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0020_history_victory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='score2',
            field=models.FloatField(default=5.5),
        ),
    ]
