# Generated by Django 3.0.3 on 2020-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0023_auto_20200229_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='last_move',
            field=models.IntegerField(default=0),
        ),
    ]
