# Generated by Django 3.0.3 on 2020-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0024_gaming_last_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='best_elo',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loserate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='winrate',
            field=models.IntegerField(default=0),
        ),
    ]
