# Generated by Django 3.0.3 on 2020-03-09 09:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0026_auto_20200309_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='moves',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), default=0, size=500),
        ),
    ]
