# Generated by Django 3.0.3 on 2020-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0027_auto_20200309_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuegame',
            name='gameName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='queuegame',
            name='random',
            field=models.IntegerField(default=0),
        ),
    ]
