# Generated by Django 3.0.3 on 2020-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0028_auto_20200321_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuegame',
            name='random',
            field=models.CharField(default='', max_length=50),
        ),
    ]
