# Generated by Django 3.0.3 on 2020-03-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0030_auto_20200321_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuegame',
            old_name='gameName',
            new_name='playerName',
        ),
    ]
