# Generated by Django 3.0.3 on 2020-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0031_auto_20200323_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuegame',
            name='refuse',
            field=models.CharField(default='', max_length=50),
        ),
    ]
