# Generated by Django 3.0.5 on 2020-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogoapp', '0032_queuegame_refuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
